module SeedCountries
	puts 'SeedCountries START'

	Country.create([
		{name: 'United Arab Emirates'},
		{name: 'Afghanistan'},
		{name: 'Albania'},
		{name: 'Armenia'},
		{name: 'Angola'},
		{name: 'Argentina'},
		{name: 'Austria'},
		{name: 'Australia'},
		{name: 'Azerbaijan'},
		{name: 'Bosnia and Herzegovina'},
		{name: 'Bangladesh'},
		{name: 'Belgium'},
		{name: 'Burkina Faso'},
		{name: 'Bulgaria'},
		{name: 'Burundi'},
		{name: 'Benin'},
		{name: 'Brunei Darussalam'},
		{name: 'Bolivia'},
		{name: 'Brazil'},
		{name: 'Bahamas'},
		{name: 'Bhutan'},
		{name: 'Botswana'},
		{name: 'Belarus'},
		{name: 'Belize'},
		{name: 'Canada'},
		{name: 'Democratic Republic of Congo'},
		{name: 'Central African Republic'},
		{name: 'Republic of Congo'},
		{name: 'Switzerland'},
		{name: 'Côte d\'Ivoire'},
		{name: 'Chile'},
		{name: 'Cameroon'},
		{name: 'China'},
		{name: 'Colombia'},
		{name: 'Costa Rica'},
		{name: 'Cuba'},
		{name: 'Cyprus'},
		{name: 'Czech Republic'},
		{name: 'Germany'},
		{name: 'Djibouti'},
		{name: 'Denmark'},
		{name: 'Dominican Republic'},
		{name: 'Algeria'},
		{name: 'Ecuador'},
		{name: 'Estonia'},
		{name: 'Egypt'},
		{name: 'Western Sahara'},
		{name: 'Eritrea'},
		{name: 'Spain'},
		{name: 'Ethiopia'},
		{name: 'Falkland Islands'},
		{name: 'Finland'},
		{name: 'Fiji'},
		{name: 'France'},
		{name: 'Gabon'},
		{name: 'United Kingdom'},
		{name: 'Georgia'},
		{name: 'French Guiana'},
		{name: 'Ghana'},
		{name: 'Greenland'},
		{name: 'Gambia'},
		{name: 'Guinea'},
		{name: 'Equatorial Guinea'},
		{name: 'Greece'},
		{name: 'Guatemala'},
		{name: 'Guinea-Bissau'},
		{name: 'Guyana'},
		{name: 'Honduras'},
		{name: 'Croatia'},
		{name: 'Haiti'},
		{name: 'Hungary'},
		{name: 'Indonesia'},
		{name: 'Ireland'},
		{name: 'Israel'},
		{name: 'India'},
		{name: 'Iraq'},
		{name: 'Iran'},
		{name: 'Iceland'},
		{name: 'Italy'},
		{name: 'Jamaica'},
		{name: 'Jordan'},
		{name: 'Japan'},
		{name: 'Kenya'},
		{name: 'Kyrgyzstan'},
		{name: 'Cambodia'},
		{name: 'North Korea'},
		{name: 'South Korea'},
		{name: 'Kosovo'},
		{name: 'Kuwait'},
		{name: 'Kazakhstan'},
		{name: 'Lao People\'s Democratic Republic'},
		{name: 'Lebanon'},
		{name: 'Sri Lanka'},
		{name: 'Liberia'},
		{name: 'Lesotho'},
		{name: 'Lithuania'},
		{name: 'Luxembourg'},
		{name: 'Latvia'},
		{name: 'Libya'},
		{name: 'Morocco'},
		{name: 'Moldova'},
		{name: 'Montenegro'},
		{name: 'Madagascar'},
		{name: 'Macedonia'},
		{name: 'Mali'},
		{name: 'Myanmar'},
		{name: 'Mongolia'},
		{name: 'Mauritania'},
		{name: 'Malawi'},
		{name: 'Mexico'},
		{name: 'Malaysia'},
		{name: 'Mozambique'},
		{name: 'Namibia'},
		{name: 'New Caledonia'},
		{name: 'Niger'},
		{name: 'Nigeria'},
		{name: 'Nicaragua'},
		{name: 'Netherlands'},
		{name: 'Norway'},
		{name: 'Nepal'},
		{name: 'New Zealand'},
		{name: 'Oman'},
		{name: 'Panama'},
		{name: 'Peru'},
		{name: 'Papua New Guinea'},
		{name: 'Philippines'},
		{name: 'Poland'},
		{name: 'Pakistan'},
		{name: 'Puerto Rico'},
		{name: 'Palestinian Territories'},
		{name: 'Portugal'},
		{name: 'Paraguay'},
		{name: 'Qatar'},
		{name: 'Romania'},
		{name: 'Serbia'},
		{name: 'Russia'},
		{name: 'Rwanda'},
		{name: 'Saudi Arabia'},
		{name: 'Solomon Islands'},
		{name: 'Sudan'},
		{name: 'Sweden'},
		{name: 'Slovenia'},
		{name: 'Svalbard and Jan Mayen'},
		{name: 'Slovakia'},
		{name: 'Sierra Leone'},
		{name: 'Senegal'},
		{name: 'Somalia'},
		{name: 'Suriname'},
		{name: 'South Sudan'},
		{name: 'El Salvador'},
		{name: 'Syria'},
		{name: 'Swaziland'},
		{name: 'Chad'},
		{name: 'French Southern and Antarctic Lands'},
		{name: 'Togo'},
		{name: 'Thailand'},
		{name: 'Tajikistan'},
		{name: 'Timor-Leste'},
		{name: 'Turkmenistan'},
		{name: 'Tunisia'},
		{name: 'Turkey'},
		{name: 'Trinidad and Tobago'},
		{name: 'Taiwan'},
		{name: 'Tanzania'},
		{name: 'Ukraine'},
		{name: 'Uganda'},
		{name: 'United States'},
		{name: 'Uruguay'},
		{name: 'Uzbekistan'},
		{name: 'Venezuela'},
		{name: 'Vietnam'},
		{name: 'Vanuatu'},
		{name: 'Yemen'},
		{name: 'South Africa'},
		{name: 'Zambia'},
		{name: 'Zimbabwe'}
	])

	puts 'SeedCountries END'
end