# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: <%= ENV["secret_key_base"] %>
  GMAIL_USERNAME: <%= ENV["GMAIL_USERNAME"] %>
  GMAIL_PASSWORD: <%= ENV["GMAIL_PASSWORD"] %>
  AWS_ACCESS_KEY_ID: <%= ENV["AWS_ACCESS_KEY_ID"] %>
  AWS_SECRET_ACCESS_KEY: <%= ENV["AWS_SECRET_ACCESS_KEY"] %>
  FOG_REGION: <%= ENV["FOG_REGION"] %>

test:
  secret_key_base: <%= ENV["secret_key_base"] %>
  GMAIL_USERNAME: <%= ENV["GMAIL_USERNAME"] %>
  GMAIL_PASSWORD: <%= ENV["GMAIL_PASSWORD"] %>

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["secret_key_base"] %>
  GMAIL_USERNAME: <%= ENV["GMAIL_USERNAME"] %>
  GMAIL_PASSWORD: <%= ENV["GMAIL_PASSWORD"] %>
