# require File.expand_path('../seeds/seed_users', __FILE__)
# require File.expand_path('../seeds/seed_countries', __FILE__)
# require File.expand_path('../seeds/seed_policies', __FILE__)
# require File.expand_path('../seeds/seed_comments', __FILE__)
# require File.expand_path('../seeds/seed_policy_votes', __FILE__)
# require File.expand_path('../seeds/seed_country_votes', __FILE__)
# require File.expand_path('../seeds/seed_user_avatars', __FILE__)